import numpy as np
import torch
from torch.utils.data import Dataset

# ══════════════════════════════════════════════════════════════════════════
# DATASET
# ══════════════════════════════════════════════════════════════════════════
class SequenceDataset(Dataset):
    """
    (num_samples, seq_len+1) tokens -> (input, target) = (x[:-1], x[1:]).
    """

    def __init__(self, seqs):
        self.seqs = np.asarray(seqs, dtype=np.int64)
        if self.seqs.ndim != 2:
            raise ValueError(f"expected (num_samples, T), got {self.seqs.shape}")
        self.seq_len = self.seqs.shape[1] - 1      # scored positions

    def __len__(self):
        return len(self.seqs)

    def __getitem__(self, idx):
        x = torch.from_numpy(self.seqs[idx])
        return x[:-1], x[1:]


# ══════════════════════════════════════════════════════════════════════════
# GENERATOR
# ══════════════════════════════════════════════════════════════════════════
from HMM_processes import (PROCESS, tokens_from_map, stationary_dist,
                           emission_dist, entropy_rate, statistical_complexity,
                           check_map)


class generator:
    def __init__(self, process: str, n_sample: int, seq_len: int, params: dict, burn_in = 100):
        if process not in PROCESS:
            raise ValueError(f"unknown process {process!r}; "
                             f"register it in HMM_processes.PROCESS "
                             f"(known: {sorted(PROCESS)})")
        self.direct = "forward" # set to backward only when self.reverse() is called;
                                #updating everything to backward model
        self.process = process
        self.n_sample = n_sample
        self.seq_len = seq_len
        self.params = params
        self.burn_in = burn_in
        self._fns = PROCESS[process]    # {transition, state_map, vocab_size}

        #generated by the method
        self.all_sequence = None
        self.input = None
        self.target = None

        #generator's causal structure
        self.vocab_size = self._vocab_size()
        self.transition = self._transition_ss_x()
        self.n_causal = self._causal_num()
        self.state_map = self._state_map()
        self.station_dist = self._station_dist()
        check_map(self.transition, self.state_map)

        #generator's quantities
        self.entropy_rate = entropy_rate(self.transition, self.state_map,
                                         self.station_dist)
        self.statistical_c = statistical_complexity(self.station_dist)

    def _transition_ss_x(self): # call functions from HMM_processes.py
        """
        state-to-state transition T[s, s'] called from HMM_processes
        """
        return self._fns["transition"](self.params)
    def _state_map(self): # call functions from HMM_processes.py
        """
        causal map E[s, s', x] = P(x | s -> s'), the token carried by each edge
        """
        return self._fns["state_map"](self.params)
    def _vocab_size(self): # call functions from HMM_processes.py
        """
        vocab size
        """
        return self._fns["vocab_size"](self.params)
    def _causal_num(self): # extracts from _transition_ss_x
        return self.transition.shape[0]
    def _station_dist(self): # extracts from _transition_ss_x
        return stationary_dist(self.transition)

    def generate(self, rng) -> np.ndarray:
        """
        (num_samples, seq_len + 1) tokens, every one of them trained on.

        `seq_len` is in TOKENS for both processes.  The +1 is the shift: the Dataset
        emits (x[:-1], x[1:]), so seq_len+1 tokens give seq_len scored positions.

        Each sequence is seeded from the stationary distribution, so it is at
        stationarity from token 0 -- for the flower that means the hub/petal
        phase is drawn per sequence rather than locked to even indices.
        `burn_in` tokens are still drawn and discarded in front of it.
        """
        tot_len = self.burn_in + self.seq_len + 1
        seqs = [tokens_from_map(tot_len, self.transition, self.state_map,
                                self.station_dist, rng)[self.burn_in:]
                for _ in range(self.n_sample)]
        out = np.stack(seqs)
        assert out.shape == (self.n_sample, self.seq_len + 1), out.shape
        self.all_sequence = out
        self.input, self.target = out[:, :-1], out[:, 1:]
        return out

    def prediction_dist(self):
        """
        p(x_{t+1}|s_t) each ideal next token prediction, shape (n_causal, vocab)
        """
        return emission_dist(self.transition, self.state_map)

    def stationary_dist(self):
        """
        pi[s] over the causal states
        """
        return self.station_dist

