import numpy as np
import torch
from torch.utils.data import DataLoader, Dataset, random_split

class SequenceDataset(Dataset):
    """
    (num_samples, seq_len+1) tokens -> (input, target) = (x[:-1], x[1:]).
    """
    def __init__(self, seqs):
        self.seqs = np.asarray(seqs, dtype=np.int64)
        if self.seqs.ndim != 2:
            raise ValueError(f"expected (num_samples, T), got {self.seqs.shape}")
        self.seq_len = self.seqs.shape[1] - 1      # scored positions
    def __len__(self):
        return len(self.seqs)
    def __getitem__(self, idx):
        x = torch.from_numpy(self.seqs[idx])
        return x[:-1], x[1:]

def split_loader(dataset, batch_size: int, test_ratio: float = 0.20, seed: int = 0):
    """
    (train_loader, test_loader) from one dataset, with a SEEDED split by sequence.

    The seed is what lets every model of a comparison -- both architectures, both
    arms -- get the same hold-out set: `random_split` without an explicit
    generator consumes the global torch RNG, so each call would draw a different
    split.  The split is by index, and generator.reverse() flips each sequence in
    place of its index, so the forward and the backward arm of one draw split
    into the same sequences.
    """
    n_test  = int(len(dataset) * test_ratio)
    n_train = len(dataset) - n_test
    tr, te = random_split(dataset, [n_train, n_test],
                          generator=torch.Generator().manual_seed(seed))
    return (DataLoader(tr, batch_size=batch_size, shuffle=True,
                       generator=torch.Generator().manual_seed(seed)),
            DataLoader(te, batch_size=batch_size, shuffle=False))

from HMM_processes import (PROCESS, tokens_from_map, stationary_dist,
                           emission_dist, entropy_rate, statistical_complexity,
                           check_map, live_map, entropy_bits, joint_map, split_map,
                           time_reverse, epsilon_machine, reverse_machine,
                           isomorphic, word_probs, filter_probs, conditional_entropies,
                           closed_class)

class generator:
    """
    One process as an object.  It starts in the forward (predictive) view.
    reverse() rewrites every direction-dependent attribute into the retrodictive
    view and flips the stored sequences; a second reverse() restores the original
    bit for bit.  check_involution() recomputes the round trip as a sanity check.
    """
    # attributes that switch with the view; n_causal, station_dist and
    # statistical_c are then recomputed from `transition` by the methods below
    VIEW_KEYS = ("transition", "state_map", "crypticity", "switching_map",
                 "gen_transition", "gen_state_map",
                 "truncated", "infinite", "C_shift", "merged")

    def __init__(self, process: str, n_sample: int, seq_len: int, params: dict, burn_in = 100,
                 tol: float = 1e-10, max_states: int = 2000):
        if process not in PROCESS:
            raise ValueError(f"unknown process {process!r}; "
                             f"register it in HMM_processes.PROCESS "
                             f"(known: {sorted(PROCESS)})")
        self.direct = "forward" # set to backward only when self.reverse() is called;
                                #updating everything to backward model
        self.process = process
        self.n_sample = n_sample
        self.seq_len = seq_len
        self.params = params
        self.burn_in = burn_in
        self.tol = tol                  # merge tolerance of the mixed-state search
        self.max_states = max_states    # cap on the mixed-state search (infinite machines)
        self._fns = PROCESS[process]    # {transition, state_map, vocab_size}

        #generated by the method
        self.all_sequence = None
        self.input = None
        self.target = None

        #the presentation written in HMM_processes: it generates the data
        self.vocab_size = self._vocab_size()
        T = self._transition_ss_x()
        E = live_map(T, self._state_map())      # p = 0 / p = 1 leave mass on dead edges
        check_map(T, E, self.vocab_size)
        keep = closed_class(T)                  # pi = 0 on transient states: never visited
        T, E = T[np.ix_(keep, keep)], E[np.ix_(keep, keep)]

        #generator's causal structure in both directions, built once
        fwd = epsilon_machine(T, E, tol, max_states)                   # M+
        bwd = reverse_machine(fwd["T"], fwd["E"], tol, max_states)     # M- = U(T(M+))
        if fwd["infinite"]:                                            # M- of a truncated M+
            bwd.update(infinite=True, truncated=bwd["truncated"] or fwd["truncated"],
                       C_shift=max(bwd["C_shift"], fwd["C_shift"]))
        pi_f, pi_b = stationary_dist(fwd["T"]), stationary_dist(bwd["T"])
        nu = bwd["mixed"]                                              # P(S+ | S-), rows = S-
        joint_pm = pi_b[:, None] * nu                                  # P(S-, S+)
        chi_plus = float(sum(pi_b[j] * entropy_bits(nu[j]) for j in range(len(pi_b))))

        #generator's quantities that do not depend on the direction
        self.entropy_rate = entropy_rate(fwd["T"], fwd["E"], pi_f)     # h- = h+ (Prop. 1)
        self.excess_entropy = statistical_complexity(pi_f) - chi_plus  # E = I[S+; S-] (Thm. 1)

        pi_g = stationary_dist(T)
        T_rev, E_rev = split_map(time_reverse(joint_map(T, E), pi_g))  # exact and finite
        flags = ("truncated", "infinite", "C_shift", "merged")
        self._views = {
            "forward": dict(transition=fwd["T"], state_map=fwd["E"],
                            crypticity=chi_plus,                                # H[S+ | S-]
                            switching_map=(joint_pm / joint_pm.sum(axis=0)).T,  # P(S- | S+)
                            gen_transition=T, gen_state_map=E,
                            **{k: fwd[k] for k in flags}),
            "backward": dict(transition=bwd["T"], state_map=bwd["E"],
                             crypticity=statistical_complexity(pi_b) - self.excess_entropy,
                             switching_map=nu,                                  # P(S+ | S-)
                             gen_transition=T_rev, gen_state_map=E_rev,
                             **{k: bwd[k] for k in flags}),
        }
        self._set_view("forward")

    def _transition_ss_x(self): # call functions from HMM_processes.py
        """
        state-to-state transition T[s, s'] called from HMM_processes
        """
        return self._fns["transition"](self.params)
    def _state_map(self): # call functions from HMM_processes.py
        """
        state map E[s, s', x] = P(x | s -> s'), the token carried by each edge
        """
        return self._fns["state_map"](self.params)
    def _vocab_size(self): # call functions from HMM_processes.py
        """
        vocab size
        """
        return self._fns["vocab_size"](self.params)
    def _causal_num(self): # extracts from self.transition (the current view)
        return self.transition.shape[0]
    def _station_dist(self): # extracts from self.transition (the current view)
        return stationary_dist(self.transition)

    def _set_view(self, direct):
        """
        expose one view: its machine, then n_causal, station_dist and statistical_c
        recomputed from that machine by the same methods as before the revision.
        """
        self.direct = direct
        for key in self.VIEW_KEYS:
            setattr(self, key, self._views[direct][key])
        self.n_causal = self._causal_num()
        self.station_dist = self._station_dist()
        self.statistical_c = statistical_complexity(self.station_dist)

    def reverse(self, check: bool = False):
        """
        rewrite the object into the other time direction.  transition, state_map,
        n_causal, station_dist, statistical_c, crypticity, switching_map, gen_*
        and the flags switch to the retrodictive machine M- (or back to M+), and the
        stored sequences are flipped in time, so that in the backward view (input,
        target) ask for x_{t-1} given x_t, x_{t+1}, ...  entropy_rate, excess_entropy
        and vocab_size do not depend on the direction.  Twice is the identity.
        """
        self._set_view("backward" if self.direct == "forward" else "forward")
        if self.all_sequence is not None:
            self.all_sequence = np.ascontiguousarray(self.all_sequence[:, ::-1])
            self.input, self.target = self.all_sequence[:, :-1], self.all_sequence[:, 1:]
        if check:
            self.check_involution()
        return self

    def generate(self, rng) -> np.ndarray:
        """
        (num_samples, seq_len + 1) tokens, every one of them trained on.
        ... Each sequence is seeded from the stationary distribution, so it is at
        stationarity from token 0 -- for the flower that means the hub/petal
        phase is drawn per sequence rather than locked to even indices.
        `burn_in` tokens are still drawn and discarded in front of it.
        Always drawn forwards from the presentation written in HMM_processes (exact
        even when the machines are infinite); in the backward view the result is
        flipped, so the same rng state gives the same data read the other way.
        """
        T, E = self._views["forward"]["gen_transition"], self._views["forward"]["gen_state_map"]
        pi = stationary_dist(T)
        tot_len = self.burn_in + self.seq_len + 1
        seqs = [tokens_from_map(tot_len, T, E, pi, rng)[self.burn_in:]
                for _ in range(self.n_sample)]
        out = np.stack(seqs)
        assert out.shape == (self.n_sample, self.seq_len + 1), out.shape
        if self.direct == "backward":
            out = np.ascontiguousarray(out[:, ::-1])
        self.all_sequence = out
        self.input, self.target = out[:, :-1], out[:, 1:]
        return out

    def prediction_dist(self):
        """
        p(x_t | s_t) each ideal next token prediction, shape (n_causal, vocab);
        in the backward view p(x_{t-1} | s-_t)
        """
        return emission_dist(self.transition, self.state_map)

    def stationary_dist(self):
        """
        pi[s] over the causal states
        """
        return self.station_dist

    def ideal_probs(self, seqs=None) -> np.ndarray:
        """
        exact P(next token | every token before it) at each position, in this view's
        reading order, shape (N, L, V): the HMM forward algorithm on gen_transition,
        gen_state_map (the time-reversed presentation in the backward view, which
        expects the flipped sequences that reverse() stores).
        """
        seqs = self.all_sequence if seqs is None else np.asarray(seqs)
        M = joint_map(self.gen_transition, self.gen_state_map)
        return filter_probs(M, stationary_dist(self.gen_transition), seqs)

    def ideal_ce(self, seqs=None) -> np.ndarray:
        """
        mean ideal cross-entropy in bits at each scored position (the targets x[:, 1:]),
        shape (seq_len,): the per-position floor for a model trained on these data.
        Its expectation decreases towards entropy_rate as the context grows.
        """
        seqs = self.all_sequence if seqs is None else np.asarray(seqs)
        P = self.ideal_probs(seqs)[:, 1:]
        p_tgt = np.take_along_axis(P, seqs[:, 1:, None], axis=2)[..., 0]
        return -np.log2(p_tgt).mean(axis=0)

    def ideal_floor(self) -> np.ndarray:
        """
        exact expected value of ideal_ce() at each scored position t = 1..seq_len:
        H[X_t | X_0 .. X_{t-1}] = h(t+1).  It is the same in both views, so a model's
        excess over it can be compared between the forward and the backward arm.
        """
        f = self._views["forward"]
        return conditional_entropies(f["gen_transition"], f["gen_state_map"], self.seq_len + 1)[1:]

    def check_involution(self, L=None, tol=1e-7) -> dict:
        """
        diagram (26) read the other way: U(T(M-)) must be M+ again.  Rebuilds the
        reverse of the backward machine from scratch, compares it with the forward
        machine, and checks the process-level identities (words, h, E).  Asserts
        for finite machines; for infinite ones it reports the gaps.
        """
        f, b = self._views["forward"], self._views["backward"]
        rep = {}
        M = joint_map(f["gen_transition"], f["gen_state_map"])
        pi = stationary_dist(f["gen_transition"])
        rep["presentation_twice"] = float(np.abs(time_reverse(time_reverse(M, pi), pi) - M).max())
        again = reverse_machine(b["transition"], b["state_map"], self.tol, self.max_states)
        rep["n_causal_again"], rep["n_causal"] = again["n_states"], f["transition"].shape[0]
        rep["isomorphic"] = isomorphic(again["T"], again["E"], f["transition"], f["state_map"], tol) is not None
        pi_a, pi_b = stationary_dist(again["T"]), stationary_dist(b["transition"])
        rep["C_again_minus_C"] = statistical_complexity(pi_a) - statistical_complexity(stationary_dist(f["transition"]))
        chi_minus_again = sum(pi_a[i] * entropy_bits(again["mixed"][i]) for i in range(len(pi_a)))
        rep["E_gap"] = abs(statistical_complexity(pi_b) - chi_minus_again - self.excess_entropy)
        V = self.vocab_size
        L = L or max(1, int(np.floor(np.log(4096) / np.log(max(V, 2)) + 1e-9)))   # V**L <= 4096
        pf = word_probs(f["transition"], f["state_map"], L)
        pb = word_probs(b["transition"], b["state_map"], L)
        pb_rev = pb.reshape((V,) * L).transpose(tuple(range(L))[::-1]).ravel()
        rep["words_L"], rep["word_prob_gap"] = L, float(np.abs(pf - pb_rev).max())
        rep["h_gap"] = abs(entropy_rate(b["transition"], b["state_map"], pi_b) - self.entropy_rate)
        rep["finite"] = not (f["infinite"] or b["infinite"])
        assert rep["presentation_twice"] < 1e-12, rep
        if rep["finite"]:
            assert rep["isomorphic"] and rep["n_causal_again"] == rep["n_causal"], rep
            assert max(rep["word_prob_gap"], rep["h_gap"], rep["E_gap"]) < tol, rep
        return rep

    def summary(self) -> dict:
        return dict(process=self.process, params=self.params, direct=self.direct,
                    vocab_size=self.vocab_size, n_causal=self.n_causal,
                    statistical_c=self.statistical_c, entropy_rate=self.entropy_rate,
                    excess_entropy=self.excess_entropy, crypticity=self.crypticity,
                    truncated=self.truncated, infinite=self.infinite, C_shift=self.C_shift)